### ISSUE TITLE
Add only the main dependencies and not the sub dependencies.

### ISSUE THREAD

**Issue by chirathr** [bksun/my-quora-app#15]
https://github.com/bksun/my-quora-app/blob/79af6ea623dd5487eafca9c35910e7d4fdfcdcee/requirements.txt#L1

**Comment by bksun** [comment]
new requirement file will have following files only:
Django==2.2.2
flake8==3.7.7
pytest==5.0.0
pytest-cov==2.7.1
pytest-django==3.5.1
